source "https://rubygems.org"

 

gem 'cucumber','1.2.1'
gem 'json','1.7.3'
gem 'net-ssh','2.5.2'
gem 'rake','0.9.2.2'
gem 'rspec','2.11.0'
gem 'selenium-webdriver','2.25.0'
gem 'trollop','1.16.2'
gem 'watir-webdriver','0.6.1'
gem 'output-to-file','1.0.3'


